project:
  type: book

book:
  title: "Spatial Data Science"
  subtitle: "with applications in R"
  author: "Edzer Pebesma, Roger Bivand"
  date: "9/2/2022"
  chapters:
    - index.qmd
    - part: 00-part-1.qmd
      chapters:
        - 01-hello.qmd
        - 02-Spaces.qmd
        - 03-Geometries.qmd
        - 04-Spherical.qmd
        - 05-Attributes.qmd
    - part: 06-part-2.qmd
      chapters:
        - 06-Cubes.qmd
        - 07-Introsf.qmd
        - 08-Large.qmd
        - 09-Plotting.qmd
    - part: 10-part-3.qmd
      chapters:
        - 10-Models.qmd
        - 13-PointPattern.qmd
        - 14-Interpolation.qmd
        - 16-Geostatistics.qmd
        - 17-Areal.qmd
        - 18-SpatialRegression.qmd
    - 30-sp-raster.qmd
    - 97-allcode.qmd
    - 98-rbascis.qmd
    - references.qmd

bibliography: all.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
    R.options:
      knitr.graphics.auto_pdf: true
      dplyr.print_min: 6
      dplyr.print_max: 6
      stars.crs: 17
      width: 66
      digits: 3

format:
  html:
    number-depth: 2
    theme: cosmo
    code-fold: false
    code-summary: "Code"
  pdf: 
    documentclass: krantz
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    pdf-engine: pdflatex
    keep-tex: true
    collapse: true
